faults/urls.py
from django.urls import path
from . import views

app_name = 'faultsapp'

urlpatterns = [
    path('', views.tfaults, name='tfaults'),
    path('tAccounts/', views.taccounts, name='taccounts'),
    path('matter_list/', views.matter_list, name='matter_list'),
]

t_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('faults.urls'))
]

faults/models.py
from django.db import models


class Matter(models.Model):
    logoid = models.CharField(max_length=7)
    logohead = models.CharField(max_length=100)
    logocust = models.CharField(max_length=100)
    whom = models.CharField(max_length=100)
    logodate = models.DateTimeField()
    logopack = models.CharField(max_length=100,default='')
    logocontent = models.TextField(default='')

faults/views.py
from django.shortcuts import render
from .models import Matter


def tfaults(request):
    return render(request, 'faultsapp/tFaults.html')


def taccounts(request):
    return render(request, 'faultsapp/tAccounts.html')


def matter_list(request):
    matters = Matter.objects.all()
    return render(request, 'faultsapp/matter_list.html', {'matters': matters})

faults/templates/faultsapp/matter_list.html
{% extends "mainpage.html" %}

{%block content%}
    <br><br><br>
<div class="container" style="width: 50%;">
<h1>Matter List</h1>
    <ol>
        {% for matter in matters %}
            <li>{{ matter.logohead }} - {{ matter.logocust }} - {{ matter.whom }} - {{ matter.logodate }} - {{ matter.logopack }}</li>
        {% endfor %}
    </ol>

{%endblock%}

faults/templates/faultsapp/tAccounts.html
{% extends "mainpage.html" %}

{%block content%}
<div class="container" style="width: 50%;">
<h1> kullnaucu bilgileriii </h1>

{%endblock%}

faults/templates/faultsapp/tFaults.html
{% extends "mainpage.html" %}

{%block content%}

{%endblock%}

templates/mainpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t_PORTAL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">t-Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">t_Portal</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">

            <a class="nav-link active" aria-current="page" href="{% url 'faultsapp:tfaults' %}">Ana Sayfa</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faultsapp:matter_list' %}">Maddeler</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hesabım
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="{% url 'faultsapp:taccounts' %}">Kullanıcı Bilgilerim</a></li>
              <li><a class="dropdown-item" href="#">Dosyalarım</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

{%block content%}

{%endblock%}

</body>
</html>